<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
  <dict>
    <key>name</key>
    <string>mcfunction</string>
    <key>scopeName</key>
    <string>source.mcfunction</string>
    <key>fileTypes</key>
    <array>
      <string>mcfunction</string>
    </array>
    <key>patterns</key>
    <array>
      <dict>
        <key>include</key>
        <string>#root</string>
      </dict>
    </array>
    <key>repository</key>
    <dict>
      <key>root</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>name</key>
            <string>keyword.control._.root_command.mcfunction</string>
            <key>match</key>
            <string>(?:\r\n|\n|^)[ \t]*[a-z][a-z0-9_]*(?=\s|$)</string>
          </dict>
          <dict>
            <key>name</key>
            <string>comment._.comment.mcfunction</string>
            <key>begin</key>
            <string>(?:\r\n|\n|^)[ \t]*(?=#)</string>
            <key>end</key>
            <string>(?=\r\n|\n|$)</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>match</key>
                <string>.+</string>
              </dict>
              <dict>
                <key>match</key>
                <string>(?:\r\n|\n|^)[ \t]*#</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>name</key>
            <string>meta._.whitespace.mcfunction</string>
            <key>match</key>
            <string>\s</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#command_tokens</string>
          </dict>
        </array>
      </dict>
      <key>command_tokens</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>name</key>
            <string>constant.numeric._.integer.command_token.mcfunction</string>
            <key>match</key>
            <string>\-?\d+(?=\s|$)</string>
          </dict>
          <dict>
            <key>name</key>
            <string>string.unquoted._.unknown.command_token.mcfunction</string>
            <key>match</key>
            <string>\S+(?=\s|$)</string>
          </dict>
        </array>
      </dict>
    </dict>
  </dict>
</plist>