<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
  <dict>
    <key>name</key>
    <string>mcfunction-snapshot</string>
    <key>scopeName</key>
    <string>source.mcfunction-snapshot</string>
    <key>fileTypes</key>
    <array>
      <string>mcfunction</string>
    </array>
    <key>patterns</key>
    <array>
      <dict>
        <key>include</key>
        <string>#comments</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#commands</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#unknown</string>
      </dict>
    </array>
    <key>repository</key>
    <dict>
      <key>comments</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>name</key>
            <string>meta.comment.todo.mcfunction</string>
            <key>match</key>
            <string>^\s*(#)\s*((?:TODO|FIXME|DELETEME)\b.*)$</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>comment.number-sign.mcfunction</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>markup.bold.mcfunction</string>
              </dict>
            </dict>
          </dict>
          <dict>
            <key>name</key>
            <string>meta.comment.annotation.mcfunction</string>
            <key>match</key>
            <string>^\s*(#)\s*(\@\w*)\b(.*)$</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>comment.number-sign.mcfunction</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>markup.bold.mcfunction</string>
              </dict>
              <key>3</key>
              <dict>
                <key>name</key>
                <string>comment.number-sign.mcfunction</string>
              </dict>
            </dict>
          </dict>
          <dict>
            <key>name</key>
            <string>meta.comment.annotation.mcfunction</string>
            <key>match</key>
            <string>^\s*(##)\s*(.*)$</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>comment.number-sign.mcfunction</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>markup.heading.mcfunction</string>
              </dict>
            </dict>
          </dict>
          <dict>
            <key>name</key>
            <string>meta.comment.mcfunction</string>
            <key>match</key>
            <string>^\s*(#.*)$</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>comment.number-sign.mcfunction</string>
              </dict>
            </dict>
          </dict>
        </array>
      </dict>
      <key>commands</key>
      <dict>
        <key>patterns</key>
        <array/>
      </dict>
      <key>unknown</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>name</key>
            <string>meta.unknown.mcfunction</string>
            <key>match</key>
            <string>^(.*)$</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>invalid.illegal.mcfunction</string>
              </dict>
            </dict>
          </dict>
        </array>
      </dict>
    </dict>
  </dict>
</plist>