<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
  <dict>
    <key>name</key>
    <string>mcfunction-snapshot</string>
    <key>scopeName</key>
    <string>source.mcfunction-snapshot</string>
    <key>fileTypes</key>
    <array>
      <string>mcfunction</string>
    </array>
    <key>patterns</key>
    <array>
      <dict>
        <key>include</key>
        <string>#comment</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#command</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#unknown</string>
      </dict>
    </array>
    <key>repository</key>
    <dict>
      <key>comment</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>name</key>
            <string>meta.comment.mcfunction</string>
            <key>begin</key>
            <string>^[ \t]*(?=\#)</string>
            <key>end</key>
            <string>\n</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#comments</string>
              </dict>
            </array>
          </dict>
        </array>
      </dict>
      <key>comments</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>name</key>
            <string>meta.comment.annotation.mcfunction</string>
            <key>match</key>
            <string>(##)[ \t]*(.*)$</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>comment.comment.mcfunction</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>markup.heading.comment.mcfunction</string>
              </dict>
            </dict>
          </dict>
          <dict>
            <key>name</key>
            <string>meta.comment.todo.mcfunction</string>
            <key>match</key>
            <string>(#)[ \t]*((?:TODO|FIXME|XXX))(\b.*)$</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>comment.comment.mcfunction</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>markup.bold.name.marker.comment.mcfunction</string>
              </dict>
              <key>3</key>
              <dict>
                <key>name</key>
                <string>comment.text.marker.comment.mcfunction</string>
              </dict>
            </dict>
          </dict>
          <dict>
            <key>name</key>
            <string>meta.comment.annotation.mcfunction</string>
            <key>match</key>
            <string>(#)[ \t]*(\@\w*)(\b.*)$</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>comment.comment.mcfunction</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>markup.heading.name.annotation.comment.mcfunction</string>
              </dict>
              <key>3</key>
              <dict>
                <key>name</key>
                <string>comment.text.annotation.comment.mcfunction</string>
              </dict>
            </dict>
          </dict>
          <dict>
            <key>name</key>
            <string>meta.comment.plain.mcfunction</string>
            <key>match</key>
            <string>(#.*)$</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>comment.comment.mcfunction</string>
              </dict>
            </dict>
          </dict>
        </array>
      </dict>
      <key>command</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>name</key>
            <string>meta.command.mcfunction</string>
            <key>begin</key>
            <string>^[ \t]*(?=[^\s\#])</string>
            <key>end</key>
            <string>\n</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#generated_commands</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#command.unknown</string>
              </dict>
            </array>
          </dict>
        </array>
      </dict>
      <key>command.unknown</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>name</key>
            <string>meta.command.unknown.mcfunction</string>
            <key>match</key>
            <string>(.*)$</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>invalid.mcfunction</string>
              </dict>
            </dict>
          </dict>
        </array>
      </dict>
      <key>unknown</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>name</key>
            <string>meta.unknown.mcfunction</string>
            <key>match</key>
            <string>^(.*)$</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>invalid.mcfunction</string>
              </dict>
            </dict>
          </dict>
        </array>
      </dict>
      <key>generated_commands</key>
      <dict>
        <key>patterns</key>
        <array/>
      </dict>
    </dict>
  </dict>
</plist>